import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    alignitems: "center",
    justifyContent: "center",
    flex: 1,
    marginLeft: 15,
    marginTop: 100,
    alignContent: "center",
  },
  entryWrapper: { marginTop: 60, alignItems: "center", paddingHorizontal: 30 },
  hadiText: {
    fontSize: 26,
    fontWeight: "800",
    color: "#111",
    alignSelf: "center",
  },
  roleText: { fontSize: 14, color: "#666", textAlign: "center", marginTop: 8 },
  rolWrapper: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 20,
  },
  card: {
    width: "47%",
    padding: 15,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#F3F4F6",
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    position: "relative",
  },
  selectedCard: { borderColor: "#22C55E", backgroundColor: "#F0FDF4" },
  imageContainer: {
    padding: 10,
    borderRadius: 50,
    backgroundColor: "#DCFCE7",
    marginBottom: 10,
  },
  imageStyle: { width: 40, height: 40 },
  cardTitle: { fontWeight: "bold", fontSize: 15 },
  cardSubText: {
    fontSize: 11,
    color: "#9CA3AF",
    textAlign: "center",
    marginTop: 4,
  },
  checkPoint: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 15,
    height: 15,
    borderRadius: 10,
    backgroundColor: "#22C55E",
  },

  inputContainer: { paddingHorizontal: 20, marginTop: 15 },
  label: { fontWeight: "600", marginBottom: 5, color: "#374151" },
  input: {
    backgroundColor: "#F9FAFB",
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    color:"black"
  },

  tipBox: {
    marginTop: 10,
    marginLeft:230,
    padding: 15,
    backgroundColor: "#F0FDF4",
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#BBF7D0",
    //marginRight: 150,
    width: 150,
    //justifyContent: "center",
    //alignItems: "center",
  },
  tipText: { color: "#166534", fontSize: 12, alignSelf: "center" },

  mainButton: {
    backgroundColor: "#22C55E",
    margin: 20,
    padding: 15,
    borderRadius: 15,
    alignItems: "center",
  },
  buttonText: { color: "white", fontWeight: "bold", fontSize: 16 },
  endWrapper: {
    marginTop: 10,
    alignItems: "center",
    paddingHorizontal: 30,
    flexDirection: "row",
  },
  girisText: {
    fontSize: 14,
    color: "#22C55E",
    textAlign: "center",
    marginTop: 8,
  },
  messageBanner: {
    position: "absolute",
    top: 10,
    left: 20,
    right: 20,
    padding: 15,
    borderRadius: 12,
    zIndex: 100,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",

    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  errorBanner: {
    backgroundColor: "#FEE2E2",
    borderWidth: 1,
    borderColor: "#FECACA",
  },
  successBanner: {
    backgroundColor: "#DCFCE7",
    borderWidth: 1,
    borderColor: "#BBF7D0",
  },
  messageText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
  },
});
